=== naaiaracj/xml/XSD_IV/Ejercicio_05/faq.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
Nombre: [Naiara Cuenca Juanas]
Curso: [ASIR1]
Fecha: [19/04/2025]
Ejercicio: [XML CON XSDIV EJ5]
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Definición del patrón para el número de versión -->
  <xs:simpleType name="versionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d+\.\d+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="qType">
    <xs:sequence>
      <xs:element name="qtext" type="xs:string"/>
      <xs:element name="a" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="partType">
    <xs:sequence>
      <xs:element name="q" type="qType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="infoType">
    <xs:sequence>
      <xs:element name="titulo" type="xs:string"/>
      <xs:element name="autor" type="xs:string"/>
      <xs:element name="email" type="xs:string" minOccurs="0"/>
      <xs:element name="version" type="versionType" minOccurs="0"/>
      <xs:element name="fecha" type="xs:date" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="faq">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="info" type="infoType"/>
        <xs:element name="part" type="partType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== naaiaracj/xml/XSD_IV/Ejercicio_05/faq.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
Nombre: [Naiara Cuenca Juanas]
Curso: [ASIR1]
Fecha: [19/04/2025]
Ejercicio: [XML CON XSDIV EJ5]
-->

<faq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="faq.xsd">
<faq>
 <info>
 <titulo>WINDOWS98? SOLO SI ME OBLIGAN!</titulo>
 <autor>Fernando Damián Lorenzo García</autor>
 <email>Fer@yahoo.es </email>
 <version>1.0</version>
 <fecha>1999-05-01</fecha>
 </info>
 <part>
 <q>
 <qtext>¿Por qué tengo que instalar W95?</qtext>
 <a> A mi también me parece una buena pregunta.</a>
 </q>
 <q>
 <qtext>Y de que me vale?</qtext>
 <a>Otra ingeniosa pregunta.</a>
 </q>
 </part>
</faq>
