<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: [Naiara Cuenca Juanas]
Curso: [ASIR1]
Fecha: [03/04/2025]
Ejercicio: [DTD5 EJ9]
-->
<!DOCTYPE mensajes [
<!-- El error es que no habia cardinalidad en mensaje -->
<!ELEMENT mensajes (mensaje)*>
<!-- El error es que el elemento mensaje no estaba definido -->
<!ELEMENT mensaje (de, para, hora, texto)>
<!ELEMENT de (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!-- El error es que strong es elemento de texto y no estaba definido -->
<!ELEMENT texto (strong)>
<!ELEMENT strong (#PCDATA)>
]>

<mensajes>
    <mensaje>
        <de>Pepe (pepe@example.com)</de>
        <para>Juan (juan@example.com)</para>
        <hora>28/02/2011 17:48:23,61</hora>
        <texto>¿Hola, Juan, qué haces?</texto>
    </mensaje>
    <mensaje>
        <de>Juan (juan@example.com)</de>
        <para>Pepe (pepe@example.com)</para>
        <hora>28/02/2011 17:54:20,87</hora>
        <texto>Aquí, aprendiendo <strong>XML</strong></texto>
    </mensaje>
</mensajes>