=== naaiaracj/xml/DTD_II/Aeropuerto/aeropuerto.dtd
<!-- Declaramos elemento raíz aeropuerto y el elemento vuelo tendrá que aparecer mínimo 1 vuelo -->
<!ELEMENT aeropuerto (nombre, vuelo+, fecha)>
<!ELEMENT nombre (#PCDATA)>
<!-- El elemento diario es opcional puede aparecer o no y es un elemento vacio por ello el EMPTY -->
<!ELEMENT vuelo (diario?, origen, destino, hora_salida, hora_llegada)>
    <!ATTLIST vuelo codigo ID #REQUIRED>
<!-- El estado del vuelo tiene que ser obligatoriamente uno de los establecidos y el estado "E" es por defecto -->
    <!ATTLIST vuelo estado (C | E | R ) "E">
<!ELEMENT diario EMPTY>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

=== naaiaracj/xml/DTD_II/Aeropuerto/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE aeropuerto SYSTEM "aeropuerto.dtd">

<aeropuerto>
    <vuelo codigo="V22" estado="R">
        <origen> New York </origen>
        <destino> Chicago </destino>
        <hora_salida> 9:30 </hora_salida>
        <hora_llegada> 11:30 </hora_llegada>
        <diario/>
    </vuelo>

    <vuelo codigo="V23" estado="C">
        <origen> New York </origen>
        <destino> Miami </destino>
        <hora_salida> 10:15 </hora_salida>
        <hora_llegada> 11:15 </hora_llegada>
    </vuelo>
    <fecha> 20/12/2013 </fecha>
</aeropuerto>
