<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: [Naiara Cuenca Juanas]
Curso: [ASIR1]
Fecha: [03/04/2025]
Ejercicio: [DTD5 EJ6]
-->
<!DOCTYPE paises [
<!-- El error es que los paises no estaba declarado para que salieran más de un país -->
<!ELEMENT paises (pais+)>
<!-- El error es que union europea y otan pueden aparecer o no por lo que hay que poner de cardinalidad * -->
<!ELEMENT pais (nombre, unionEuropea*, otan*)>
<!ELEMENT nombre EMPTY>
<!ELEMENT unionEuropea EMPTY>
<!ELEMENT otan EMPTY>
]>

<paises> 
    <pais>
        <nombre>España</nombre>
        <unionEuropea /> 
        <otan />
    </pais> 
    <pais>
        <nombre>Noruega</nombre> 
        <otan />
    </pais> 
    <pais>
        <nombre>Austria</nombre>
        <unionEuropea />
    </pais> 
</paises>
