<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: [Naiara Cuenca Juanas]
Curso: [ASIR1]
Fecha: [02/04/2025]
Ejercicio: [DTD5 EJ2]
-->
<!-- El error es que el elemento efemeride debe tener la cardinalidad + o * ya que hay más de un elemento efemeride en el documento xml -->
<!DOCTYPE efemerides [
    <!ELEMENT efemerides (efemeride)>
    <!ELEMENT efemeride (fecha, hecho)>
<!-- El error es que no se han declarado los elementos fecha y hecho -->
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT hecho (#PCDATA)>
]>

<efemerides>
    <efemeride>
        <fecha>20 de julio de 1969</fecha>
        <hecho>Llegada del hombre a la luna</hecho>
    </efemeride>
    <efemeride>
        <fecha>12 de octubre de 1492</fecha>
        <hecho>Llegada de Colón a América</hecho>
    </efemeride>
    <efemeride>
        <fecha>6 de abril de 1909</fecha>
        <hecho>Llegada de Robert Peary al Polo Norte</hecho>
    </efemeride>
</efemerides>